### ISSUE TITLE
Improper formatted JourneyDetailRef url

### ISSUE THREAD

**Issue by marcelbuesing** [dbopendata/db-fahrplan-api#10]
I think the second `?` in the url should actually be a `&`.

```
http://open-api.bahn.de/bin/rest.exe/v1.0/journeyDetail?ref=358707/120803/425950/93406/80?date=2016-01-01&station_evaId=8000105&station_type=dep&authKey=zzz&lang=en&format=json&
```

I think it should actually look like this:

```
http://open-api.bahn.de/bin/rest.exe/v1.0/journeyDetail?ref=358707/120803/425950/93406/80&date=2016-01-01&station_evaId=8000105&station_type=dep&authKey=zzz&lang=en&format=json&
```

**Comment by thekonz** [comment]
Also, the protocol shoul be `https`, or at least match the protocol of the initial *Board request.

**Comment by highsource** [comment]
+1

**Comment by highsource** [comment]
@marcelbuesing No, not quite. You should not interpret the `ref` param as a part of this URL. The JSON response contains URLs with the `ref` parameter in encoded form:

```
http://open-api.bahn.de/bin/rest.exe/v1.0/journeyDetail?ref=210711%2F74511%2F223578%2F41552%2F80%3Fdate%3D2016-02-22%26station_evaId%3D8000105%26station_type%3Darr%26authKey%3Dzzz%26lang%3Dde%26format%3Djson
```

Which may look weird but is not a malformed URL.

I believe implementation behind the API simple takes the `ref` parameter and appends it to some base URL. In this case, the encoded `?` (which you mean to be the second `?`) makes sense. Probably the build it into something like:

```
http://some.internal/url/358707/120803/425950/93406/80?date=2016-01-01&station_evaId=8000105&station_type=dep&authKey=zzz&lang=en&format=json&
```

**Comment by highsource** [comment]
@thekonz Agreed, but that's another issue.

**Comment by highsource** [comment]
@thekonz See #15.

**Comment by highsource** [comment]
Closing as invalid.
